package com.bbva.achp.risklimitsbehavioralevaluationsv0.business.v0.impl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.junit.MockitoJUnitRunner;

@RunWith(MockitoJUnitRunner.class)
public class RiskLimitsListBehavioralEvaluationsV0BusinessTest {

  @InjectMocks private RiskLimitsListBehavioralEvaluationsV0Business bSrv;

  @Test
  public void testRiskLimitsListBehavioralEvaluationsV0() {
    // TODO: Autogenerated source. This test must be implemented.
    bSrv.riskLimitsListBehavioralEvaluationsV0("customerid");
  }
}
